### ISSUE TITLE
Third-party arabic extension doesn't work

### ISSUE THREAD

**Issue by papageorgiouk** [pkra/mathjax-node-page#60]
Passing the extension like:

```
var mjpageconfig = {
    .
    .
    extensions: '[Contrib]/arabic/arabic.js', // a convenience option to add MathJax extensions
    .
};
```

doesn't work with (test) latin characters, and if i pass arabic characters an error is thrown:

```
Error: Uncaught [TypeError: Cannot read property 'GLYPH' of undefined]
```

I tried passing a custom `mathjax-node` instance based on [pull request #391](https://github.com/mathjax/MathJax-node/pull/391) (the one that allows custom third-party extensions), and following its [instructions](https://github.com/Edraak/arabic-mathjax#how-to-use-the-extension). Still no luck.

**Comment by pkra** [comment]
Unfortunately, `arabic.js` only supports MathJax's HTML-CSS output which mathjax-node does not support (since that output is ancient and creates client-specific code).

I know Omar is hoping to upgrade `arabic.js` but I'm guessing he'll wait for MathJax v3 to do so (which will also run directly in Node).

**Comment by pkra** [comment]
I'm closing this for now. Feel free to re-open if neede.d

**Comment by papageorgiouk** [comment]
Alright, cheers 👍
