### ISSUE TITLE
is there a way to limit the memory usage?

### ISSUE THREAD

**Issue by Ir1d** [pkra/mathjax-node-page#72]
Hi, I have a lot of equations in a page, it seems that using mathjax-node-page consumes too much memory.
I wonder if there's a way to limit this?
Thx in advance.

**Comment by pkra** [comment]
>  I wonder if there's a way to limit this?

There are currently no built-in methods for doing that. There are some obvious improvements I never got around to implementing (e.g. the big while loop should be refactored so that it waits until one typeset is complete instead of queuing all of them). But I'm currently not planning to do significant work on this library because of #54. 

Of course, pull requests are always welcome.

**Comment by Ir1d** [comment]
Thx for informing! I'm really looking forward to v3.
